services:

  hw:
    tty: true
    build:
      context: .
    volumes:
      - ./hello_world:/usr/src/myapp
    working_dir: /usr/src/myapp
    # command: ["run"]

  ex1:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./example_1:/usr/src/myapp
    working_dir: /usr/src/myapp
    # command: ["run"]

  ex2:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./example_2:/usr/src/myapp
    working_dir: /usr/src/myapp
    # command: ["run"]
  
  ex3:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./example_3:/usr/src/myapp
    working_dir: /usr/src/myapp
    # command: ["run"]